Add vk group support
PiterPy-Meetup/postpost pull request #12
Opened 2019-01-27 19:59 UTC by vladimirshkoda

Add some functions

2019-01-27 20:40 UTC, b0g3r requested changes

2019-01-27 20:40 UTC, b0g3r commented on postpost/api/vkontakte.py
> +    Returns a string with url for authorization.
Стоит дописать, что используется для получения access-token'а, возможно приложить ссылочку или пример использования

2019-01-27 20:40 UTC, b0g3r commented on postpost/api/tasks.py
> +    vk_response = vkontakte.send_post_to_group(
Я бы здесь сделал более высокоуровнево: просто функция, которая принимает пост. А внутри уже экстрактится текст, аттачменты и прикидывается в низкоуровневую функцию

2019-01-27 20:40 UTC, b0g3r commented on postpost/api/tasks.py
> +    if vk_response.status_code != requests.codes.ok or 'error' in vk_response.json():
Но тогда надо подумать где делать вот эту проверку, наверное тоже в vkontakte.py

2019-01-29 18:44 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApi(object):
А зачем такое?
Мне не нравится идея делать класс ради группировки группы методов

2019-01-29 18:46 UTC, b0g3r requested changes

2019-01-29 18:46 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApiError(Exception):
Правило именования флейка настойчиво просит именовать аббревиатуры как аббревиатуры: `api` и `API`, но не `Api`

2019-01-29 19:00 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApi(object):
В разговоре услышал. Напиши в докстринг, что эти методы объеденены в класс, так как во всех них используется общий для запросов токен и всякое такое

2019-01-29 19:02 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApi(object):
Возможно стоит `VkAPI`

2019-01-29 20:31 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +    Returns a string with url for authorization.
Сделано.

2019-01-29 20:31 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +class VkApiError(Exception):
Сейчас исправлю.

2019-01-29 20:31 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +class VkApi(object):
Напишу в док-стринг и переименую.

2019-01-29 20:32 UTC, vladimirshkoda commented on postpost/api/tasks.py
> +    vk_response = vkontakte.send_post_to_group(
Это я сделаю в будущем каком-нибудь коммите, потому что сейчас непонятно что пост будет содержать.

2019-01-29 20:33 UTC, vladimirshkoda commented on postpost/api/tasks.py
> +    if vk_response.status_code != requests.codes.ok or 'error' in vk_response.json():
Вынес эту проверку внутрь VkAPI клиента.

2019-01-30 06:21 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApiError(Exception):
Если как мы решили в разговоре делать с True/False+error (привет, go), то можно и без экспешена обойтись

2019-01-30 06:21 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApiError(Exception):
При этом внутри бы `send_post_to_group` я бы не писал изменения PlatformPost, я бы делал установку статуса и установку ошибки всё равно снаружи посылалки, т.е. что-то такое
```success, error_text = send_post_to_vk(platform_post)  # return Tuple[bool, Optional[str]]
if success:
  # set status success
else:
  # set status failed
  # set error text 
```
а всё важное логировать где-то внутри send_post_to_vk, наружу отдавать только чистый интерфейсик

2019-01-30 06:21 UTC, b0g3r commented on postpost/api/vkontakte.py
> +    def upload_doc(self, doc_path: str) -> str:
Я бы либо в названии метода, либо бы в докстринге явно указал, что это используется у нас для гифок

2019-01-30 06:21 UTC, b0g3r commented on postpost/api/tasks.py
> +    try:
В try-except рекомендую засовывать только ту строчку, которая приведет к эксепшену, иначе код внутри разрастается

2019-01-30 06:29 UTC, vladimirshkoda commented on postpost/api/tasks.py
> +    try:
Дак а как ты поменяешь статус поста в зависимости от того, запостился он или нет? Ещё одну переменную заводить?

2019-01-30 06:29 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +    def upload_doc(self, doc_path: str) -> str:
Окей

2019-01-30 06:33 UTC, b0g3r commented on postpost/api/tasks.py
> +    try:
try-except-else?
А вообще я тут где-то в комментариях предлагал избавляться снаружи от переменных :thinking:

2019-01-30 06:34 UTC, b0g3r commented on postpost/api/tasks.py
> +    try:
Ой, у меня там ещё появилось, пойду откоментирую

2019-01-30 06:37 UTC, b0g3r commented on postpost/api/vkontakte.py
> +class VkApiError(Exception):
Вот тут я писал, что наружу возвращать статус и ошибку, но этого не хватит :(

Я уверен, что следующим шагом мы захотим хранить айдишники полученных постов или ещё чего-нибудь и тогда универсально сделать уже не получится. Пока пусть останется как есть, мне кажется это не критично. На следующей итерации поймём как лучше сделать

2019-01-30 07:44 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +    def upload_doc(self, doc_path: str) -> str:
Хотя нет, не окей: там потом вылезет какая-нибудь необходимость прикрепить док или таблицу, или ещё что-нибудь.

2019-01-30 07:45 UTC, vladimirshkoda commented on postpost/api/tasks.py
> +    try:
Пока всё равно не понятно, где эту логику будем хранить, оставляю так.

2019-01-30 07:53 UTC, vladimirshkoda reviewed
Короче, на данной итерации оставляю всё как есть, потому что работает и потому что непонятно, как это обобщить с другими соцсетями.

2019-01-30 19:19 UTC, b0g3r submitted a review, later dismissed

2019-01-30 19:21 UTC, b0g3r commented
Мне кажется codacy должен починиться с следующим пушем

2019-01-31 15:04 UTC, teners commented on postpost/api/vkontakte.py
> +        )['upload_url']
А не упадёт как-нибудь тут с KeyError?

2019-01-31 15:04 UTC, teners commented on postpost/api/vkontakte.py
> +        response = requests.post(upload_url, files={'file': open(photo_path, 'rb')})
Вот тут (и где-то ещё где файлы открываешь), может, всё-таки, в переменную файл открывать и проверять что он на самом деле открылся? Ты OSError тут не ловишь

2019-01-31 15:05 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +        )['upload_url']
Упадёт ещё в self._request, если что-то не так. Если всё так, то ссылку должен вернуть

2019-01-31 15:08 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +        response = requests.post(upload_url, files={'file': open(photo_path, 'rb')})
Ну хз, лучше вообще file-like object сюда передавать, как по мне, типа какой-нибудь IO.

2019-01-31 15:14 UTC, teners commented on postpost/api/vkontakte.py
> +        response = requests.post(upload_url, files={'file': open(photo_path, 'rb')})
Ну я не предлагаю оставить как есть и просто ловить OSError, я имею в виду, что написано как написано, и _даже_ не ловишь экспешон

2019-01-31 15:15 UTC, teners commented on postpost/api/vkontakte.py
> +        )['upload_url']
Fair enough

2019-02-03 09:14 UTC, vladimirshkoda commented on postpost/api/vkontakte.py
> +        response = requests.post(upload_url, files={'file': open(photo_path, 'rb')})
Done

2019-02-04 11:53 UTC, teners approved these changes
lgtm, for now 🤷‍♀️

2019-02-04 13:36 UTC, merged