Add telegram gate.
PiterPy-Meetup/postpost pull request #21
Opened 2019-02-09 16:16 UTC by vladimirshkoda

Closes #3 
- Add a tiny tg api client.
- Add a general function to post to telegram.
- Change the function task to call the general function.

2019-02-09 18:00 UTC, b0g3r requested changes

2019-02-09 18:00 UTC, b0g3r commented on postpost/api/telegram.py
> +        return requests.get(self._url + 'getMe').json()
_request?

2019-02-11 12:15 UTC, vladimirshkoda commented on postpost/api/telegram.py
> +        return requests.get(self._url + 'getMe').json()
_request шлёт post, я подумал, что get достаточно. Или телеграмму всё равно, каким методом приходит запрос?

2019-02-12 12:53 UTC, teners submitted a review, later dismissed

2019-02-12 12:53 UTC, teners commented on postpost/api/telegram.py
> +        return requests.get(self._url + 'getMe').json()
@vladimirshkoda 
> We support GET and POST HTTP methods. Use either URL query string or application/json or application/x-www-form-urlencoded or multipart/form-data for passing parameters in Bot API requests.

А че @b0g3r имеет в виду я не понял

2019-02-12 13:25 UTC, b0g3r commented on postpost/api/telegram.py
> +        return requests.get(self._url + 'getMe').json()
я имел в виду, что мы написали специальную обёрточку _request с обработкой ошибок, и в одном месте её не используем

2019-02-12 19:54 UTC, vladimirshkoda commented on postpost/api/telegram.py
> +        return requests.get(self._url + 'getMe').json()
@teners @b0g3r я и говорю: _request отправляет POST и делает проверку на статус. Если статус != ок, то поднимается исключение. Я не уверен, что это нужно для того, чтобы пингануть бота.

2019-02-13 18:59 UTC, b0g3r approved these changes
Спасибо за уделённое время и правки! Мне всё сейчас нравится, давай дождёмся ещё одного апрува. @PiterPy-Meetup/postpost-dev, что скажете?

2019-02-13 20:50 UTC, teners approved these changes

2019-02-13 20:50 UTC, teners commented
@vladimirshkoda 👌 cool

2019-02-13 20:51 UTC, b0g3r commented
🎉 
поздравляю с ещё одним мёрджем!

2019-02-13 21:28 UTC, merged