Add mypy requirement and define dev packages.
PiterPy-Meetup/postpost pull request #22
Opened 2019-02-13 10:12 UTC by vladimirshkoda

Add mypy requirement and define dev packages.

2019-02-13 17:10 UTC, teners submitted a review, later dismissed

2019-02-13 18:44 UTC, b0g3r commented
А исправлять найденные нарушения в отдельном репо? 🤔

2019-02-13 19:18 UTC, teners commented
@b0g3r таски заведи))0

2019-02-13 19:20 UTC, b0g3r commented
> @b0g3r таску заведи))0

Ну хз, я против такого: если я начну свою ветку от девелопа после мёрджа этого PR, то мне придётся либо игнорировать "чужие" ошибки, либо исправлять их и править несвязанные с моей таской файлы.

2019-02-13 19:23 UTC, teners commented
Ну эту тему уже кто-то пропустил и мы помёржили в дев-ветку, щито поделать
Если @vladimirshkoda сможет поправить, будет огонь, конечно, я че против что ли

2019-02-13 19:27 UTC, b0g3r commented
Я за фикс в этой ветке, короче.

Руководствуюсь такой логикой: если мы добавим, например, [safety](https://pypi.org/project/safety/) check в CI, то найденные зависимости с уязвимостями нужно будет поправить в том же MR, что добавляет `safety`

2019-02-14 15:47 UTC, teners submitted a review, later dismissed
Местами, конечно, из-за преколов тайпинга выглядит диковато, но ладно

2019-02-14 15:49 UTC, vladimirshkoda commented
@teners согласен более, чем полностью. Но учитывая, что мы там всё будем править, а сейчас важно просто прикрутить проверки для CI -- можно смириться.

2019-02-14 16:07 UTC, b0g3r commented on postpost/api/serializers.py
> +        serializer: serializers.ModelSerializer = self.serializers_by_type.get(
ачто если тип указать у serializers_by_type как Dict[str, serializers.ModelSerializer]

2019-02-14 16:10 UTC, b0g3r commented on setup.cfg
> +    # Doesn't work properly so far
Оставь, пожалуйста, ссылку на ишьюс, чтобы знать когда это убрать

2019-02-14 16:10 UTC, b0g3r commented on postpost/api/vkontakte.py
> +        saved_photo: Dict[str, Any] = self._request(
а здесь ругается если _request уже затипизирован? 🤔

2019-02-14 16:10 UTC, b0g3r commented on postpost/api/vkontakte.py
> +        saved_photo: Dict[str, Any] = self._request(
а, понял, там дальше идёт вложенность

2019-02-14 16:10 UTC, b0g3r commented on .travis.yml
> +  - 'pipenv run mypy .'
возможно стоит ещё подобрать конфиги построже под mypy в setup.cfg

2019-02-14 18:59 UTC, vladimirshkoda commented on .travis.yml
> +  - 'pipenv run mypy .'
Взял у Соболева

2019-02-14 19:03 UTC, vladimirshkoda commented on postpost/api/serializers.py
> +        serializer: serializers.ModelSerializer = self.serializers_by_type.get(
Ты самый умный тут что ли

2019-02-14 19:04 UTC, vladimirshkoda commented on setup.cfg
> +    # Doesn't work properly so far
Оставил

2019-02-14 21:41 UTC, b0g3r requested changes

2019-02-14 21:41 UTC, b0g3r commented on Pipfile
> +wemake-python-styleguide = "==0.7.1"
Это же дев-зависимость

2019-02-14 21:41 UTC, b0g3r commented on postpost/api/models/platform_settings.py
>      PLATFORM_TYPES = [
Это тоже Final

2019-02-14 21:41 UTC, b0g3r commented on postpost/api/serializers.py
> +from api.custom_types import JSON
Я бы вынес custom_types.py выше, в postpost

2019-02-14 21:41 UTC, b0g3r commented on postpost/api/serializers.py
> +        representation: Dict[str, str] = serializer().to_representation(platform_settings)
Это неправда ведь, значения не строки

2019-02-14 21:41 UTC, b0g3r commented on postpost/api/vkontakte.py
> +        saved_photo: JSON = self._request(
Я думаю, что здесь дополнительная типизация не нужна

2019-02-15 06:52 UTC, b0g3r commented on postpost/custom_types.py
> +JSON = typing.Union[  # type: ignore
А зачем type: ignore?

2019-02-15 06:59 UTC, vladimirshkoda commented on postpost/custom_types.py
> +JSON = typing.Union[  # type: ignore
Выпадает ворнинг о том, что рекурсивные типы не до конца ещё поддерживаются

2019-02-15 09:02 UTC, vladimirshkoda commented on postpost/custom_types.py
> +JSON = typing.Union[  # type: ignore
Добавил ссылку на issue.

2019-02-15 11:01 UTC, teners approved these changes

2019-02-15 11:07 UTC, b0g3r approved these changes
Спасибо за вклад и уделённое время! Надеюсь, что это спасёт нас не один раз от будущих ошибок <3

2019-02-15 11:15 UTC, merged